---
title: "Education & Teaching"
---

## Qualifications

**PhD (Statistics)** 

- RMIT University, 2018

**Grad.Cert (Teaching & Learning in Higher Education)**

- Swinburne University, 2017

**Masters by Research (Statistics)** 

- RMIT University, 2011

**Bachelors (Psychology)**

- RMIT University, 2008


## Positions

**Monash University (2025 – present)**

  - Senior Lecturer
  - Deputy Director Education (Econometrics & Business Statistics)

**La Trobe University (2020 – 2025)**

  - Lecturer / Senior Lecturer
  - Course Coordinator (Sport & Exercise Science)

**Swinburne University (2015 – 2019)**

  - Associate Lecturer / Lecturer
  - Major Displine Coordiantor (Applied Statistics)

## Teaching

**Monash University (2025 – present)**

  - ETC2420/ETC5242 (Statistical Thinking)
  - ETC1000 (Business and Economic Statistics)

**La Trobe University (2020 – 2025)**

- SPE5SAP (Sport Analytics in Practice)
- SPE5AMS (Analytical Methods in Sport)
- SPE2DSS (Data Science and Statistics in Sport)

**Swinburne University (2015 – 2019)**

- STA2006 (Analysis of variance and regression)
- STA2004 (Sport Statistics)
- STA3005 (Multivariate Statistics)
- STA2008 (Forensic Statistics)
- STA2009 (Epidemiology)
- STA3003 (Health Statistics)






